language: php

php:
    - 7.0
    - 7.1

before_script:
    - "composer self-update"
    - "composer --version"
    - "composer install --verbose --ignore-platform-reqs"

script:
    - "vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover"

after_script:
    - "wget https://scrutinizer-ci.com/ocular.phar"
    - "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"